<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ResearchHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\ResearchHandler.php';

return $this->privates['App\Services\ResearchHandler'] = new \App\Services\ResearchHandler(($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')));
