<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\CheckUserRoleService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\CheckUserRoleService.php';

return $this->privates['App\Services\CheckUserRoleService'] = new \App\Services\CheckUserRoleService();
