<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.d9aQ9np' shared service.

return $this->privates['service_locator.d9aQ9np'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('researchHandler' => function (): ?\App\Services\ResearchHandler {
    return ($this->privates['App\Services\ResearchHandler'] ?? $this->load(__DIR__.'/getResearchHandlerService.php'));
}));
