<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\CheckOutHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\CheckOutHandler.php';

return $this->privates['App\Services\CheckOutHandler'] = new \App\Services\CheckOutHandler(($this->privates['App\Services\SubscribeDataGenerator\FlusherService'] ?? $this->load(__DIR__.'/getFlusherServiceService.php')));
