framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    csrf_protection: true
    #http_method_override: true

    # uncomment this entire section to enable sessions
    #session:
    #    # With this config, PHP's native session handling is used
    #    handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    validation: { enable_annotations: true }
