<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ArticleListDataGenerator\ListArticleService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\ArticleListDataGenerator\\ListArticleService.php';

return $this->privates['App\Services\ArticleListDataGenerator\ListArticleService'] = new \App\Services\ArticleListDataGenerator\ListArticleService(($this->privates['App\Repository\ArticleRepository'] ?? $this->load(__DIR__.'/getArticleRepositoryService.php')));
