<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.KhTx4ja' shared service.

return $this->privates['service_locator.KhTx4ja'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('checkout' => function (): ?\App\Services\CheckOutHandler {
    return ($this->privates['App\Services\CheckOutHandler'] ?? $this->load(__DIR__.'/getCheckOutHandlerService.php'));
}));
