<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\DeleteArticleHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\DeleteArticleHandler.php';

return $this->privates['App\Services\DeleteArticleHandler'] = new \App\Services\DeleteArticleHandler(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()));
