<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\SubscribeDataGenerator\FlusherService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\SubscribeDataGenerator\\FlusherService.php';

return $this->privates['App\Services\SubscribeDataGenerator\FlusherService'] = new \App\Services\SubscribeDataGenerator\FlusherService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')));
