<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\NewArticleHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\NewArticleHandler.php';

return $this->privates['App\Services\NewArticleHandler'] = new \App\Services\NewArticleHandler(($this->privates['App\Services\SubscribeDataGenerator\FlusherService'] ?? $this->load(__DIR__.'/getFlusherServiceService.php')), ($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php')), $this, ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()));
