<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.VXkrEKb' shared service.

return $this->privates['service_locator.VXkrEKb'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('denyhand' => function (): ?\App\Services\DenyObsHandler {
    return ($this->privates['App\Services\DenyObsHandler'] ?? $this->load(__DIR__.'/getDenyObsHandlerService.php'));
}));
