<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.BTVloeW' shared service.

return $this->privates['service_locator.BTVloeW'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mapHandler' => function (): ?\App\Services\MapHandler {
    return ($this->privates['App\Services\MapHandler'] ?? $this->load(__DIR__.'/getMapHandlerService.php'));
}));
