<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.cumVKIr' shared service.

return $this->privates['service_locator.cumVKIr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('validatehand' => function (): ?\App\Services\ValidateObsHandler {
    return ($this->privates['App\Services\ValidateObsHandler'] ?? $this->load(__DIR__.'/getValidateObsHandlerService.php'));
}));
