<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\DashboardHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\DashboardHandler.php';

return $this->privates['App\Services\DashboardHandler'] = new \App\Services\DashboardHandler();
