<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjMM8Zi\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjMM8Zi/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJjMM8Zi.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerJjMM8Zi\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerJjMM8Zi\srcProdProjectContainer(array(
    'container.build_hash' => 'JjMM8Zi',
    'container.build_id' => '26882177',
    'container.build_time' => 1516918747,
));
