<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\DashboardHandler' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\common\\lib\\Doctrine\\Common\\Persistence\\ObjectRepository.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\collections\\lib\\Doctrine\\Common\\Collections\\Selectable.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\EntityRepository.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\doctrine-bridge\\Security\\User\\UserLoaderInterface.php';
include_once $this->targetDirs[3].'\\src\\Repository\\UserRepository.php';
include_once $this->targetDirs[3].'\\src\\Services\\DashboardHandler.php';

return $this->privates['App\Services\DashboardHandler'] = new \App\Services\DashboardHandler(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), new \App\Repository\UserRepository(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php'))));
