<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.oTHV_I7' shared service.

return $this->privates['service_locator.oTHV_I7'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('articleService' => function (): ?\App\Services\ArticleService {
    return ($this->privates['App\Services\ArticleService'] ?? $this->load(__DIR__.'/getArticleServiceService.php'));
}));
