<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.R6oaVOY' shared service.

return $this->privates['service_locator.R6oaVOY'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('subscribeHandler' => function (): ?\App\Services\SubscribeHandler {
    return ($this->privates['App\Services\SubscribeHandler'] ?? $this->load(__DIR__.'/getSubscribeHandlerService.php'));
}));
