<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.chain_provider' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\User\\UserProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\User\\ChainUserProvider.php';

return $this->privates['security.user.provider.concrete.chain_provider'] = new \Symfony\Component\Security\Core\User\ChainUserProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['security.user.provider.concrete.in_memory'] ?? $this->load(__DIR__.'/getSecurity_User_Provider_Concrete_InMemoryService.php'));
    yield 1 => ($this->privates['security.user.provider.concrete.db_provider'] ?? $this->load(__DIR__.'/getSecurity_User_Provider_Concrete_DbProviderService.php'));
}, 2));
