<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\UserFixerService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\UserFixerService.php';

return $this->privates['App\Services\UserFixerService'] = new \App\Services\UserFixerService(($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php')));
