<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.6G1AhUG' shared service.

return $this->privates['service_locator.6G1AhUG'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('modifyHandler' => function (): ?\App\Services\ModifyUserHandler {
    return ($this->privates['App\Services\ModifyUserHandler'] ?? $this->load(__DIR__.'/getModifyUserHandlerService.php'));
}));
