<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\DashboardHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\DashboardDataGenerator\\AdminDashboard.php';
include_once $this->targetDirs[3].'\\src\\Services\\DashboardDataGenerator\\UserDashboard.php';
include_once $this->targetDirs[3].'\\src\\Services\\DashboardDataGenerator\\OrganizerDashboard.php';
include_once $this->targetDirs[3].'\\src\\Services\\DashboardHandler.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php'));

return $this->privates['App\Services\DashboardHandler'] = new \App\Services\DashboardHandler(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), new \App\Services\DashboardDataGenerator\AdminDashboard($a, ($this->privates['App\Services\ArticleListDataGenerator\ListArticleService'] ?? $this->load(__DIR__.'/getListArticleServiceService.php'))), ($this->services['security.token_storage'] ?? $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()), $a, new \App\Services\DashboardDataGenerator\UserDashboard(), new \App\Services\DashboardDataGenerator\OrganizerDashboard());
