<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ModifyArticleHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\ModifyArticleHandler.php';

return $this->privates['App\Services\ModifyArticleHandler'] = new \App\Services\ModifyArticleHandler(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), ($this->privates['App\Services\SubscribeDataGenerator\FlusherService'] ?? $this->load(__DIR__.'/getFlusherServiceService.php')), ($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php')));
