<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.MAB7qRx' shared service.

return $this->privates['service_locator.MAB7qRx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('donHandler' => function (): ?\App\Services\DonHandler {
    return ($this->privates['App\Services\DonHandler'] ?? $this->load(__DIR__.'/getDonHandlerService.php'));
}));
