#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


blog_list:
    path: /blog
    controller: 'App\Controller\BlogController::list'

user:
    path: /user
    controller: 'App\Controller\UserController::index' 

user/subscribe:
    path: /user/subscribe
    controller: 'App\Controller\UserController::subscribe'
    
don:
    path: /don
    controller: 'App\Controller\DonController::index'