#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

home:
    path: /
    controller: App\Controller\HomeController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index