<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.rWoBfLf' shared service.

return $this->privates['service_locator.rWoBfLf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('downgradeUHandler' => function (): ?\App\Services\DowngradeUserHandler {
    return ($this->privates['App\Services\DowngradeUserHandler'] ?? $this->load(__DIR__.'/getDowngradeUserHandlerService.php'));
}));
