<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\SubscribeHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\SubscribeDataGenerator\\CheckUserRoleService.php';
include_once $this->targetDirs[3].'\\src\\Services\\SubscribeDataGenerator\\UserFixerService.php';
include_once $this->targetDirs[3].'\\src\\Services\\SubscribeHandler.php';

return $this->privates['App\Services\SubscribeHandler'] = new \App\Services\SubscribeHandler(($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php')), ($this->privates['App\Services\SubscribeDataGenerator\FlusherService'] ?? $this->load(__DIR__.'/getFlusherServiceService.php')), new \App\Services\SubscribeDataGenerator\CheckUserRoleService(), new \App\Services\SubscribeDataGenerator\UserFixerService(($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php'))));
