<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.mK_71Bz' shared service.

return $this->privates['service_locator.mK_71Bz'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('singleHandler' => function (): ?\App\Services\SingleArticleHandler {
    return ($this->privates['App\Services\SingleArticleHandler'] ?? $this->load(__DIR__.'/getSingleArticleHandlerService.php'));
}));
