<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.srmxvxF' shared service.

return $this->privates['service_locator.srmxvxF'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailer' => function (): ?\App\Services\Mailer {
    return ($this->privates['App\Services\Mailer'] ?? $this->load(__DIR__.'/getMailerService.php'));
}));
