<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ArticleService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\ArticleService.php';

return $this->privates['App\Services\ArticleService'] = new \App\Services\ArticleService(($this->privates['App\Repository\ArticleRepository'] ?? $this->load(__DIR__.'/getArticleRepositoryService.php')));
