<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.udmBeas' shared service.

return $this->privates['service_locator.udmBeas'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('articleService' => function (): ?\App\Services\ArticleListDataGenerator\ListArticleService {
    return ($this->privates['App\Services\ArticleListDataGenerator\ListArticleService'] ?? $this->load(__DIR__.'/getListArticleServiceService.php'));
}));
