<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2BBRR3h\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2BBRR3h/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2BBRR3h.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2BBRR3h\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2BBRR3h\srcDevDebugProjectContainer();
