<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\Upload' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\Upload.php';

return $this->privates['App\Services\Upload'] = new \App\Services\Upload($this);
